### ISSUE TITLE
Rollback

### ISSUE THREAD

**Issue by LaganYT** [alexwohlbruck/jukebox#10]
Until you have the time to develop the new version could you rollback the master branch?

**Comment by LaganYT** [comment]
What is the variable GOOGLE_SERVER_KEY for? And where do i get it?

**Comment by alexwohlbruck** [comment]
Hey, I preferred to merge the dev branch I had been working on since it included some features I wanted that didn't exist in the other version. That being said, its been a number of years since I worked on this and lots of maintenance isn't something I have a lot of time to prioritize at the moment. It seems like you've attempted to fork the project and get it running locally? If so, I can help you out with that.

To get the project running, you will just need to install the required packages with npm or yarn, and create a `.env` file with the following fields:

```
SPOTIFY_CLIENT_ID = xxxxxxxxxxxxxxxxxxxxx
SPOTIFY_CLIENT_SECRET = xxxxxxxxxxxxxxxxxxxxx
GOOGLE_SERVER_KEY = xxxxxxxxxxxxxxxxxxxxx
```

To get the Google server key, head to the [Google Cloud Platform](https://console.cloud.google.com) website, create a project and go to the APIs and Services page. Then Enable the `Youtube Data API V3`. You should be able to generate a server API key, which will be the value to put in your `.env` file.

Then, log in to the [Spotify Developer Console](https://developer.spotify.com/dashboard), and create a new app. Once created, you should get Client ID and Client Secret keys, which are the other two values for your `.env` file.

Then, just run the server with `npm start` or `yarn start`.

**Comment by LaganYT** [comment]
What is the build command?

**Comment by alexwohlbruck** [comment]
There isn't one, the server runs live JS and the frontend is old-school Angular. Frontend runs on localhost:8080

**Comment by LaganYT** [comment]
Then how do i host from heroku? Im confused. Do i run commands in the command run?

**Comment by alexwohlbruck** [comment]
Create a new heroku app and add the `heroku/nodejs` buildpack. Then deploy using the method of your choice.

**Comment by LaganYT** [comment]
What is the node version?

**Comment by alexwohlbruck** [comment]
It is working for me on 14.19.1, but should work for most all versions.

**Comment by LaganYT** [comment]
Ok so i got it working. Just wondering what causes the synced music? I want to get rid of it. Also how do i have the player go to the next song on the album when the last song is over?
